'use strict';
const caseData={
 commerce:{index:'01',sector:'E-COMMERCE GROWTH',value:'50萬<span class="mi metric-direction" aria-hidden="true">arrow_forward</span><span class="sr-only">成長至</span>1億+',unit:'電商年營收 · 兩百倍級成長',title:'從電商建置，走向事業經營',description:'以電商事業的經營視角，串聯營運、平台體驗與商業績效。',steps:[['商業視角','結合 P&L 與 ROI，理解營運表現。'],['平台落地','從 UI/UX 到 UAT，串聯金物流整合。']],tags:['E-COMMERCE','P&L / ROI','UI/UX · UAT']},
 experience:{index:'02',sector:'CUSTOMER EXPERIENCE',value:'+10<span>%</span>',unit:'站內轉換率提升',title:'用新的體驗，縮短購買的距離',description:'導入 AI 推薦與 AR 試戴，優化消費者在線上選擇商品的體驗。',steps:[['AI 推薦','以推薦機制連結消費者與商品。'],['AR 試戴','將試戴體驗帶進電商購物流程。']],tags:['AI 推薦','AR 試戴','轉換優化']},
 efficiency:{index:'03',sector:'MARKETING EFFICIENCY',value:'−25<span>%+</span>',unit:'CPA 降低 25% 以上',title:'讓行銷資源，發揮整合的效益',description:'跨線上線下整合 OMO 資源，降低 CPA，提升行銷投放的效率。',steps:[['OMO 整合','串聯線上與線下接觸點。'],['成效管理','以數據與 ROI 觀察行銷資源運用。']],tags:['OMO','ROI','CPA']},
 campaign:{index:'04',sector:'CAMPAIGN PERFORMANCE',value:'+20<span>%+</span>',unit:'大檔期業績 YoY 成長',title:'關鍵檔期，把策略化為成長動能',description:'在雙 11、618 等大檔期，達成業績年增 20% 以上，並連續多年達標。',steps:[['檔期推進','整合雙 11、618 等重要購物節奏。'],['執行整合','協同跨部門與外部合作資源。']],tags:['雙 11','618','整合行銷']},
 retention:{index:'05',sector:'MEMBER RELATIONSHIPS',value:'34<span>%</span>',unit:'CRM 會員再購率',title:'從一次交易，走向長期關係',description:'透過 CRM、會員分群與再行銷經營會員關係，關注顧客長期價值。',steps:[['會員洞察','運用 CRM 與會員分群理解顧客。'],['關係經營','以再行銷延續互動，關注 LTV。']],tags:['CRM','會員分群','LTV']}
};
const careerData={
 brand:{company:'FORMOSA OPTICAL',title:'行銷部經理／電商事業主管',english:'Marketing Manager & Head of E-Commerce',description:'2017 年起在寶島眼鏡，整合行銷與電商事業，帶領 5 人團隊，串聯商業目標、平台體驗與會員經營。',points:['電商年營收由 50 萬成長至 1 億以上，兩百倍級成長。','推動 AI 推薦、AR 試戴與 OMO，優化購物體驗及行銷效率。','規劃 EYE+ Pay 流程、定義需求，協同廠商與跨部門推進。'],bottom:['2017 — NOW','團隊 5 人','行銷 × 電商事業']},
 agency:{company:'4A AGENCY',title:'副業務總監',english:'Associate Account Director',description:'2008 至 2017 年於廣告代理，擔任副業務總監，推進跨媒體整合行銷，從市場洞察到高複雜度專案執行。',points:['過往服務品牌包含中國信託、中華電信、台灣啤酒、YAMAHA 與米其林輪胎。','參與台灣啤酒「18 天生搶鮮喝」專案，獲 2013 時報華文廣告金像獎。','參與經典台啤「經典超時光飛行」專案，獲 2014 金手指網路獎。'],bottom:['2008 — 2017','廣告代理','客戶服務 × 品牌溝通']}
};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function animatePanel(panel){panel.classList.remove('changing');void panel.offsetWidth;panel.classList.add('changing')}
function selectCase(key,{focus=false}={}){const d=caseData[key];if(!d)return;$$('.case-tab').forEach(b=>{const active=b.dataset.case===key;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active&&focus)b.focus()});$('#case-sector').textContent=d.sector;$('#case-value').innerHTML=d.value;$('#case-unit').textContent=d.unit;$('#case-number').textContent=d.index+' / 05';$('#case-title').textContent=d.title;$('#case-description').textContent=d.description;$('#case-steps').replaceChildren(...d.steps.map(([title,text],i)=>{const el=document.createElement('div');el.className='case-step';const number=document.createElement('span');number.textContent=String(i+1).padStart(2,'0');const p=document.createElement('p');const strong=document.createElement('strong');strong.textContent=title;p.append(strong,document.createTextNode(text));el.append(number,p);return el}));$('#case-tags').replaceChildren(...d.tags.map(t=>{const s=document.createElement('span');s.textContent=t;return s}));$('#case-panel').setAttribute('aria-labelledby','tab-'+key);animatePanel($('#case-panel'))}
function bindTabs(buttons,key,select,vertical=false){buttons.forEach((button,index)=>{button.addEventListener('click',()=>select(button.dataset[key]));button.addEventListener('keydown',event=>{let next=index;const horizontal=!vertical||matchMedia('(max-width:760px)').matches;const forward=horizontal?'ArrowRight':'ArrowDown';const backward=horizontal?'ArrowLeft':'ArrowUp';if(event.key===forward)next=(index+1)%buttons.length;else if(event.key===backward)next=(index-1+buttons.length)%buttons.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=buttons.length-1;else return;event.preventDefault();select(buttons[next].dataset[key],{focus:true});buttons[next].scrollIntoView({block:'nearest',inline:'nearest',behavior:'auto'})})})}
bindTabs($$('.case-tab'),'case',selectCase);
$$('[data-case-link]').forEach(b=>b.addEventListener('click',()=>{selectCase(b.dataset.caseLink);$('#impact').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#tab-'+b.dataset.caseLink).focus({preventScroll:true})}));
function selectCareer(key,{focus=false}={}){const d=careerData[key];if(!d)return;$$('.career-tab').forEach(b=>{const active=b.dataset.career===key;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active&&focus)b.focus()});$('#career-company').textContent=d.company;$('#career-title').textContent=d.title;$('#career-english').textContent=d.english;$('#career-description').textContent=d.description;$('#career-points').replaceChildren(...d.points.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));$('#career-bottom').replaceChildren(...d.bottom.map(text=>{const span=document.createElement('span');span.textContent=text;return span}));$('#career-panel').setAttribute('aria-labelledby','career-tab-'+key);animatePanel($('#career-panel'))}
bindTabs($$('.career-tab'),'career',selectCareer,true);
const careerMobile=matchMedia('(max-width:760px)');function syncCareerOrientation(){$('.career-tabs').setAttribute('aria-orientation',careerMobile.matches?'horizontal':'vertical')}careerMobile.addEventListener('change',syncCareerOrientation);syncCareerOrientation();
const dialog=$('#intro-dialog');const frame=$('#intro-frame');let introOpener=null;
$$('.intro-trigger').forEach(b=>b.addEventListener('click',()=>{introOpener=b;if(!frame.getAttribute('src'))frame.src=frame.dataset.src;dialog.showModal();document.body.style.overflow='hidden';$('#close-intro').focus()}));
function closeIntro(){frame.contentWindow?.postMessage({type:'sunny-intro',action:'pause'},location.origin==='null'?'*':location.origin);dialog.close()}
$('#close-intro').addEventListener('click',closeIntro);dialog.addEventListener('click',e=>{if(e.target===dialog){const box=dialog.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)closeIntro()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';frame.contentWindow?.postMessage({type:'sunny-intro',action:'pause'},location.origin==='null'?'*':location.origin);introOpener?.focus()});
$('#print-resume').addEventListener('click',()=>window.print());selectCase('commerce');selectCareer('brand');
