
(()=>{'use strict';const S=JSON.parse(document.getElementById('scene-data').textContent),D=83.84,$=id=>document.getElementById(id);const svg=$('film'),groups=[...svg.querySelectorAll('.scene')],seek=$('seek'),voice=$('voice');let t=0,playing=false,speed=1,last=0,raf=0,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,hasAudio=true,emitAt=0,audioURL=null;const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>1-Math.pow(1-clamp(v),3),fmt=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(Math.floor(n%60)).padStart(2,'0');if(new URLSearchParams(location.search).get('embed')==='1')document.body.classList.add('embed');
$('chapters').innerHTML=S.map((s,i)=>`<button class="chapter" data-index="${i}" aria-current="${i===0}"><small>${String(i+1).padStart(2,'0')} / ${fmt(s.start)}</small><span>${s.title}</span></button>`).join('');$('transcript').innerHTML=S.map(s=>`<p><strong>${fmt(s.start)} ${s.title}</strong><br>${s.narration}</p>`).join('');
const reveal=[...svg.querySelectorAll('[data-in]')],paths=[...svg.querySelectorAll('[data-draw]')];paths.forEach(el=>{el.dataset.length=el.getTotalLength();el.style.strokeDasharray=el.dataset.length});
function setMotion(){ $('motion').setAttribute('aria-pressed',String(reduced)); }setMotion();
function draw(time){t=clamp(time,0,D);let ix=S.findIndex(s=>t>=s.start&&t<s.end);if(ix<0)ix=S.length-1;const scene=S[ix],local=t-scene.start;groups.forEach((g,i)=>{const ss=S[i],elapsed=t-ss.start;let opacity=(elapsed>=0&&t<ss.end)?1:0;if(i===S.length-1&&t>=ss.end)opacity=1;g.style.display=opacity?'inline':'none';g.setAttribute('aria-hidden',String(!opacity));g.style.opacity=opacity;});
reveal.forEach(el=>{const st=Number(el.closest('.scene').dataset.start),q=ease((t-st-Number(el.dataset.in))/Number(el.dataset.dur||.85));el.style.opacity=reduced?(t>=st?1:0):q;el.setAttribute('transform',`translate(${reduced?0:(1-q)*Number(el.dataset.dx||0)} ${reduced?0:(1-q)*Number(el.dataset.dy||28)})`)});
paths.forEach(el=>{const st=Number(el.closest('.scene').dataset.start),q=reduced?1:ease((t-st-Number(el.dataset.draw))/Number(el.dataset.dur||1.5));el.style.strokeDashoffset=Number(el.dataset.length)*(1-q)});
svg.querySelectorAll('[data-rotate]').forEach(el=>{const st=Number(el.closest('.scene').dataset.start);const [cx,cy,rate]=el.dataset.rotate.split(',').map(Number);el.setAttribute('transform',`rotate(${reduced?0:Math.max(0,t-st)*rate} ${cx} ${cy})`)});
svg.querySelectorAll('[data-travel]').forEach(el=>{const st=Number(el.closest('.scene').dataset.start),p=svg.querySelector('#'+el.dataset.travel),period=Number(el.dataset.period||7),start=Number(el.dataset.offset||0);let prog=reduced?.65:((Math.max(0,t-st)+start)%period)/period;const pt=p.getPointAtLength(p.getTotalLength()*prog);el.setAttribute('transform',`translate(${pt.x} ${pt.y})`)});
svg.querySelectorAll('[data-scale]').forEach(el=>{const st=Number(el.closest('.scene').dataset.start),q=ease((t-st-Number(el.dataset.scale))/1.3);const [cx,cy]=el.dataset.origin.split(',').map(Number),sc=reduced?1:.08+.92*q;el.setAttribute('transform',`translate(${cx} ${cy}) scale(${sc}) translate(${-cx} ${-cy})`)});
const cap=scene.captions.find(c=>local>=c.at&&local<c.until);$('captions').textContent=cap?cap.text:scene.captions[scene.captions.length-1].text;seek.value=t;seek.setAttribute('aria-valuetext',`${fmt(t)}，共 ${fmt(D)}，${scene.title}`);$('clock').textContent=fmt(t)+' / '+fmt(D);document.querySelectorAll('.chapter').forEach((b,i)=>{b.setAttribute('aria-current',String(i===ix));b.style.setProperty('--progress',`${i<ix?100:i===ix?clamp(local/(scene.end-scene.start))*100:0}%`)});if(parent!==window&&performance.now()-emitAt>500){parent.postMessage({type:'sunny-intro-state',time:t,playing,duration:D},'*');emitAt=performance.now()}}
function audioTime(){return hasAudio&&isFinite(voice.duration)&&voice.duration>0?voice.currentTime:t}function syncAudio(){if(hasAudio&&isFinite(voice.duration)){voice.currentTime=Math.min(t,voice.duration);voice.playbackRate=speed}}
function icon(){ $('play').setAttribute('aria-label',playing?'暫停動畫':'播放動畫');$('playIcon').textContent=playing?'pause':'play_arrow'; }
function frame(now){if(!playing)return;if(!last)last=now;const dt=Math.min((now-last)/1000,.25);last=now;draw(hasAudio?(voice.paused?t:audioTime()):t+dt*speed);if(t>=D){pause();return}raf=requestAnimationFrame(frame)}
function play(){if(t>=D-.01)draw(0);if(playing)return;playing=true;last=0;syncAudio();if(hasAudio)voice.play().catch(()=>{hasAudio=false;$('audioStatus').textContent='瀏覽器未能播放音訊，已切回字幕版；可重整後再按播放'});icon();raf=requestAnimationFrame(frame)}function pause(){playing=false;cancelAnimationFrame(raf);voice.pause();icon()}function goto(time){draw(time);syncAudio()}function replay(){pause();goto(0);play()}$('play').onclick=()=>playing?pause():play();$('replay').onclick=replay;seek.oninput=e=>goto(Number(e.target.value));$('speed').onchange=e=>{speed=Number(e.target.value);voice.playbackRate=speed};$('cc').onclick=()=>{const off=$('captions').classList.toggle('off');$('cc').setAttribute('aria-pressed',String(!off))};$('motion').onclick=()=>{reduced=!reduced;setMotion();draw(t)};$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else $('stageWrap').requestFullscreen?.()};$('chapters').onclick=e=>{const b=e.target.closest('[data-index]');if(b)goto(S[Number(b.dataset.index)].start+.01)};document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();playing?pause():play()}if(e.code==='ArrowRight'){e.preventDefault();goto(t+5)}if(e.code==='ArrowLeft'){e.preventDefault();goto(t-5)}if(e.key.toLowerCase()==='r')replay();if(e.key.toLowerCase()==='m'){reduced=!reduced;setMotion();draw(t)}});
$('mute').onclick=()=>{voice.muted=!voice.muted;$('mute').setAttribute('aria-pressed',String(voice.muted));$('mute').textContent=voice.muted?'已靜音':'聲音開'};$('loadAudio').onclick=()=>$('audioFile').click();$('audioFile').onchange=e=>{const file=e.target.files[0];if(!file)return;pause();if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(file);voice.src=audioURL;voice.onloadedmetadata=()=>{hasAudio=true;goto(t);$('audioStatus').textContent=`已載入本機配音：${file.name} · ${fmt(voice.duration)}`;$('audioExplain').textContent='音訊僅在本機播放器內使用，並未上傳。章節與字幕依原配音排定；替換音訊可能無法逐句對齊。'};voice.onerror=()=>{hasAudio=false;$('audioStatus').textContent='音訊格式無法讀取，請改用 MP3、WAV 或 M4A。'}};voice.onended=()=>{draw(D);pause()};window.addEventListener('message',e=>{if(e.source!==parent&&e.source!==window)return;const d=e.data;if(!d||d.type!=='sunny-intro')return;if(d.action==='play')play();if(d.action==='pause')pause();if(d.action==='seek'&&Number.isFinite(d.time))goto(d.time)});window.sunnyIntro={play,pause,seek:goto,replay,get state(){return{time:t,playing,duration:D}}};draw(0);if(parent!==window)parent.postMessage({type:'sunny-intro-ready',duration:D},'*');
})();